#!/bin/bash

# Names of HTTP Replica Server Hosts

hostname_HTTP=(ec2-52-0-73-113.compute-1.amazonaws.com
                ec2-52-16-219-28.eu-west-1.compute.amazonaws.com
                ec2-52-11-8-29.us-west-2.compute.amazonaws.com
                ec2-52-8-12-101.us-west-1.compute.amazonaws.com
                ec2-52-28-48-84.eu-central-1.compute.amazonaws.com
                ec2-52-68-12-77.ap-northeast-1.compute.amazonaws.com
                ec2-52-74-143-5.ap-southeast-1.compute.amazonaws.com
                ec2-52-64-63-125.ap-southeast-2.compute.amazonaws.com
                ec2-54-94-214-108.sa-east-1.compute.amazonaws.com)


# DNS Hostname

hostname_DNS=cs5700cdnproject.ccs.neu.edu


# Use shift in while loop to parse command line arguments

while [ $# -gt 0 ]
do
    case $1 in
        --origin | -o)
            shift;;
        --name | -n)
            shift;;
        --port | -p)
            shift;;
        --username | -u)
            shift; u_name=$1;;
        --identity | -i)
            shift; private_key=$1;;
        *)
            usage;;
    esac
    shift
done


# Stop DNS Server and kill all daughter processes

ret=`ssh -i $private_key $u_name@$hostname_DNS "ps aux | grep $u_name.*dnsserver | grep -v grep" | awk '{ print $2 }' | head -1`
ssh -i $private_key $u_name@$hostname_DNS "kill -9 $ret && ps aux | grep $u_name.*dnsserver >/dev/null 2>&1 &"


# Stop all HTTP Replica Servers and kill their daughter processes

for data in ${hostname_HTTP[@]};
do 
        ret=`ssh -i $private_key $u_name@$data "ps aux | grep $u_name.*httpserver | grep -v grep" | awk '{ print $2 }' | head -1`
        ssh -i $private_key $u_name@$data "kill -9 $ret && ps aux | grep $u_name.*httpserver >/dev/null 2>&1 &"
done




